#!/usr/bin/env python3
"""Bake a monospace bitmap font into a C++ table.

The engine draws its own UI, so it needs glyphs without pulling in a text
shaping library. This renders printable ASCII from a system TrueType face
once, at a size chosen so the advance is an exact pixel count, and emits a
row-per-byte bitmap the renderer can blit directly.

Regenerate with:
    python3 engine/tools/make_font.py > engine/src/render/FontData.inl
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CELL_W, CELL_H = 7, 13          # glyph cell in pixels
PT = 13                         # point size that fits that cell
FIRST, LAST = 32, 126           # printable ASCII

def main():
    font = ImageFont.truetype(FONT_PATH, PT)
    ascent, _ = font.getmetrics()
    # Nudge glyphs into the cell: baseline near the bottom, a little left
    # bearing trimmed so the advance lands on CELL_W.
    origin_y = min(ascent, CELL_H - 2)

    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (CELL_W, CELL_H), 0)
        d = ImageDraw.Draw(img)
        d.text((0, origin_y), chr(code), font=font, fill=255, anchor="ls")
        glyph = []
        for y in range(CELL_H):
            bits = 0
            for x in range(CELL_W):
                # A pixel counts as ink past the halfway point; the font is
                # antialiased and the target is 1-bit.
                if img.getpixel((x, y)) > 110:
                    bits |= 1 << x
            glyph.append(bits)
        rows.append((code, glyph))

    out = sys.stdout
    out.write("// Generated by engine/tools/make_font.py -- do not edit by hand.\n")
    out.write("// %d x %d cell, printable ASCII %d..%d, one byte per row,\n"
              % (CELL_W, CELL_H, FIRST, LAST))
    out.write("// bit 0 is the leftmost pixel.\n\n")
    out.write("namespace forge {\nnamespace fontdata {\n\n")
    out.write("constexpr int kCellWidth  = %d;\n" % CELL_W)
    out.write("constexpr int kCellHeight = %d;\n" % CELL_H)
    out.write("constexpr int kFirstChar  = %d;\n" % FIRST)
    out.write("constexpr int kLastChar   = %d;\n\n" % LAST)
    out.write("constexpr unsigned char kGlyphs[][%d] = {\n" % CELL_H)
    for code, glyph in rows:
        label = chr(code) if code != 92 else "backslash"
        if code == 32:
            label = "space"
        out.write("    { %s },  // %d '%s'\n"
                  % (", ".join("0x%02x" % b for b in glyph), code, label))
    out.write("};\n\n} // namespace fontdata\n} // namespace forge\n")

if __name__ == "__main__":
    main()
